version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    groups:
      dev-deps:
        patterns: ["pytest*", "mypy*", "ruff*", "twine*"]
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
